// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: ksem.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Timestamp from google protobuf
type Timestamp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seconds       int64                  `protobuf:"varint,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
	Nanos         int32                  `protobuf:"varint,2,opt,name=nanos,proto3" json:"nanos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Timestamp) Reset() {
	*x = Timestamp{}
	mi := &file_ksem_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Timestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timestamp) ProtoMessage() {}

func (x *Timestamp) ProtoReflect() protoreflect.Message {
	mi := &file_ksem_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timestamp.ProtoReflect.Descriptor instead.
func (*Timestamp) Descriptor() ([]byte, []int) {
	return file_ksem_proto_rawDescGZIP(), []int{0}
}

func (x *Timestamp) GetSeconds() int64 {
	if x != nil {
		return x.Seconds
	}
	return 0
}

func (x *Timestamp) GetNanos() int32 {
	if x != nil {
		return x.Nanos
	}
	return 0
}

// GDRs - Grid Data Records (multiple GDR messages)
type GDRs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GDRs          map[string]*GDR        `protobuf:"bytes,1,rep,name=GDRs,proto3" json:"GDRs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ConfigUuid    string                 `protobuf:"bytes,2,opt,name=configUuid,proto3" json:"configUuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GDRs) Reset() {
	*x = GDRs{}
	mi := &file_ksem_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GDRs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GDRs) ProtoMessage() {}

func (x *GDRs) ProtoReflect() protoreflect.Message {
	mi := &file_ksem_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GDRs.ProtoReflect.Descriptor instead.
func (*GDRs) Descriptor() ([]byte, []int) {
	return file_ksem_proto_rawDescGZIP(), []int{1}
}

func (x *GDRs) GetGDRs() map[string]*GDR {
	if x != nil {
		return x.GDRs
	}
	return nil
}

func (x *GDRs) GetConfigUuid() string {
	if x != nil {
		return x.ConfigUuid
	}
	return ""
}

// GDR - Single Grid Data Record
type GDR struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"` // 0=UNKNOWN, 1=OK, 2=WARNING, 3=ERROR
	Timestamp     *Timestamp             `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Values        map[uint64]uint64      `protobuf:"bytes,4,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // OBIS code -> value
	FlexValues    map[string]*FlexValue  `protobuf:"bytes,5,rep,name=flexValues,proto3" json:"flexValues,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GDR) Reset() {
	*x = GDR{}
	mi := &file_ksem_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GDR) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GDR) ProtoMessage() {}

func (x *GDR) ProtoReflect() protoreflect.Message {
	mi := &file_ksem_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GDR.ProtoReflect.Descriptor instead.
func (*GDR) Descriptor() ([]byte, []int) {
	return file_ksem_proto_rawDescGZIP(), []int{2}
}

func (x *GDR) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GDR) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GDR) GetTimestamp() *Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *GDR) GetValues() map[uint64]uint64 {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *GDR) GetFlexValues() map[string]*FlexValue {
	if x != nil {
		return x.FlexValues
	}
	return nil
}

// FlexValue for flexible data types
type FlexValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IntValue      int64                  `protobuf:"varint,1,opt,name=intValue,proto3" json:"intValue,omitempty"`
	StringValue   string                 `protobuf:"bytes,2,opt,name=stringValue,proto3" json:"stringValue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlexValue) Reset() {
	*x = FlexValue{}
	mi := &file_ksem_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlexValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlexValue) ProtoMessage() {}

func (x *FlexValue) ProtoReflect() protoreflect.Message {
	mi := &file_ksem_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlexValue.ProtoReflect.Descriptor instead.
func (*FlexValue) Descriptor() ([]byte, []int) {
	return file_ksem_proto_rawDescGZIP(), []int{3}
}

func (x *FlexValue) GetIntValue() int64 {
	if x != nil {
		return x.IntValue
	}
	return 0
}

func (x *FlexValue) GetStringValue() string {
	if x != nil {
		return x.StringValue
	}
	return ""
}

// GCRs - Grid Config Records (multiple GCR messages)
type GCRs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GCRs          map[string]*GCR        `protobuf:"bytes,1,rep,name=GCRs,proto3" json:"GCRs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ConfigUuid    string                 `protobuf:"bytes,2,opt,name=configUuid,proto3" json:"configUuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GCRs) Reset() {
	*x = GCRs{}
	mi := &file_ksem_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GCRs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GCRs) ProtoMessage() {}

func (x *GCRs) ProtoReflect() protoreflect.Message {
	mi := &file_ksem_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GCRs.ProtoReflect.Descriptor instead.
func (*GCRs) Descriptor() ([]byte, []int) {
	return file_ksem_proto_rawDescGZIP(), []int{4}
}

func (x *GCRs) GetGCRs() map[string]*GCR {
	if x != nil {
		return x.GCRs
	}
	return nil
}

func (x *GCRs) GetConfigUuid() string {
	if x != nil {
		return x.ConfigUuid
	}
	return ""
}

// GCR - Single Grid Config Record
type GCR struct {
	state           protoimpl.MessageState     `protogen:"open.v1"`
	Id              string                     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Label           string                     `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Class           int32                      `protobuf:"varint,3,opt,name=class,proto3" json:"class,omitempty"` // 0=UNKNOWN, 1=CONSUMER, 2=PRODUCER, 3=HYBRID
	Sources         []string                   `protobuf:"bytes,4,rep,name=sources,proto3" json:"sources,omitempty"`
	Codes           []uint64                   `protobuf:"varint,5,rep,packed,name=codes,proto3" json:"codes,omitempty"`
	Devicetype      int32                      `protobuf:"varint,6,opt,name=devicetype,proto3" json:"devicetype,omitempty"`
	Meta            map[string]string          `protobuf:"bytes,7,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp       *Timestamp                 `protobuf:"bytes,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	FlexDefinitions map[string]*FlexDefinition `protobuf:"bytes,9,rep,name=flexDefinitions,proto3" json:"flexDefinitions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GCR) Reset() {
	*x = GCR{}
	mi := &file_ksem_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GCR) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GCR) ProtoMessage() {}

func (x *GCR) ProtoReflect() protoreflect.Message {
	mi := &file_ksem_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GCR.ProtoReflect.Descriptor instead.
func (*GCR) Descriptor() ([]byte, []int) {
	return file_ksem_proto_rawDescGZIP(), []int{5}
}

func (x *GCR) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GCR) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *GCR) GetClass() int32 {
	if x != nil {
		return x.Class
	}
	return 0
}

func (x *GCR) GetSources() []string {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *GCR) GetCodes() []uint64 {
	if x != nil {
		return x.Codes
	}
	return nil
}

func (x *GCR) GetDevicetype() int32 {
	if x != nil {
		return x.Devicetype
	}
	return 0
}

func (x *GCR) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *GCR) GetTimestamp() *Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *GCR) GetFlexDefinitions() map[string]*FlexDefinition {
	if x != nil {
		return x.FlexDefinitions
	}
	return nil
}

// FlexDefinition for flexible field definitions
type FlexDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Type          int32                  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"` // 0=INTEGER, 1=STRING
	Unit          int32                  `protobuf:"varint,3,opt,name=unit,proto3" json:"unit,omitempty"` // 0=UNKNOWN, 1=AMPERE, 2=VOLT, 3=WATT, etc.
	Decimalpower  int32                  `protobuf:"zigzag32,4,opt,name=decimalpower,proto3" json:"decimalpower,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlexDefinition) Reset() {
	*x = FlexDefinition{}
	mi := &file_ksem_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlexDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlexDefinition) ProtoMessage() {}

func (x *FlexDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_ksem_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlexDefinition.ProtoReflect.Descriptor instead.
func (*FlexDefinition) Descriptor() ([]byte, []int) {
	return file_ksem_proto_rawDescGZIP(), []int{6}
}

func (x *FlexDefinition) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *FlexDefinition) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *FlexDefinition) GetUnit() int32 {
	if x != nil {
		return x.Unit
	}
	return 0
}

func (x *FlexDefinition) GetDecimalpower() int32 {
	if x != nil {
		return x.Decimalpower
	}
	return 0
}

var File_ksem_proto protoreflect.FileDescriptor

const file_ksem_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"ksem.proto\x12\x05proto\";\n" +
	"\tTimestamp\x12\x18\n" +
	"\aseconds\x18\x01 \x01(\x03R\aseconds\x12\x14\n" +
	"\x05nanos\x18\x02 \x01(\x05R\x05nanos\"\x96\x01\n" +
	"\x04GDRs\x12)\n" +
	"\x04GDRs\x18\x01 \x03(\v2\x15.proto.GDRs.GDRsEntryR\x04GDRs\x12\x1e\n" +
	"\n" +
	"configUuid\x18\x02 \x01(\tR\n" +
	"configUuid\x1aC\n" +
	"\tGDRsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12 \n" +
	"\x05value\x18\x02 \x01(\v2\n" +
	".proto.GDRR\x05value:\x028\x01\"\xd5\x02\n" +
	"\x03GDR\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12.\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x10.proto.TimestampR\ttimestamp\x12.\n" +
	"\x06values\x18\x04 \x03(\v2\x16.proto.GDR.ValuesEntryR\x06values\x12:\n" +
	"\n" +
	"flexValues\x18\x05 \x03(\v2\x1a.proto.GDR.FlexValuesEntryR\n" +
	"flexValues\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\x1aO\n" +
	"\x0fFlexValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.proto.FlexValueR\x05value:\x028\x01\"I\n" +
	"\tFlexValue\x12\x1a\n" +
	"\bintValue\x18\x01 \x01(\x03R\bintValue\x12 \n" +
	"\vstringValue\x18\x02 \x01(\tR\vstringValue\"\x96\x01\n" +
	"\x04GCRs\x12)\n" +
	"\x04GCRs\x18\x01 \x03(\v2\x15.proto.GCRs.GCRsEntryR\x04GCRs\x12\x1e\n" +
	"\n" +
	"configUuid\x18\x02 \x01(\tR\n" +
	"configUuid\x1aC\n" +
	"\tGCRsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12 \n" +
	"\x05value\x18\x02 \x01(\v2\n" +
	".proto.GCRR\x05value:\x028\x01\"\xca\x03\n" +
	"\x03GCR\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x14\n" +
	"\x05class\x18\x03 \x01(\x05R\x05class\x12\x18\n" +
	"\asources\x18\x04 \x03(\tR\asources\x12\x14\n" +
	"\x05codes\x18\x05 \x03(\x04R\x05codes\x12\x1e\n" +
	"\n" +
	"devicetype\x18\x06 \x01(\x05R\n" +
	"devicetype\x12(\n" +
	"\x04meta\x18\a \x03(\v2\x14.proto.GCR.MetaEntryR\x04meta\x12.\n" +
	"\ttimestamp\x18\b \x01(\v2\x10.proto.TimestampR\ttimestamp\x12I\n" +
	"\x0fflexDefinitions\x18\t \x03(\v2\x1f.proto.GCR.FlexDefinitionsEntryR\x0fflexDefinitions\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aY\n" +
	"\x14FlexDefinitionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.proto.FlexDefinitionR\x05value:\x028\x01\"r\n" +
	"\x0eFlexDefinition\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x12\n" +
	"\x04type\x18\x02 \x01(\x05R\x04type\x12\x12\n" +
	"\x04unit\x18\x03 \x01(\x05R\x04unit\x12\"\n" +
	"\fdecimalpower\x18\x04 \x01(\x11R\fdecimalpowerB&Z$github.com/mgoeppe/ksem/pkg/protob\x06proto3"

var (
	file_ksem_proto_rawDescOnce sync.Once
	file_ksem_proto_rawDescData []byte
)

func file_ksem_proto_rawDescGZIP() []byte {
	file_ksem_proto_rawDescOnce.Do(func() {
		file_ksem_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ksem_proto_rawDesc), len(file_ksem_proto_rawDesc)))
	})
	return file_ksem_proto_rawDescData
}

var file_ksem_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_ksem_proto_goTypes = []any{
	(*Timestamp)(nil),      // 0: proto.Timestamp
	(*GDRs)(nil),           // 1: proto.GDRs
	(*GDR)(nil),            // 2: proto.GDR
	(*FlexValue)(nil),      // 3: proto.FlexValue
	(*GCRs)(nil),           // 4: proto.GCRs
	(*GCR)(nil),            // 5: proto.GCR
	(*FlexDefinition)(nil), // 6: proto.FlexDefinition
	nil,                    // 7: proto.GDRs.GDRsEntry
	nil,                    // 8: proto.GDR.ValuesEntry
	nil,                    // 9: proto.GDR.FlexValuesEntry
	nil,                    // 10: proto.GCRs.GCRsEntry
	nil,                    // 11: proto.GCR.MetaEntry
	nil,                    // 12: proto.GCR.FlexDefinitionsEntry
}
var file_ksem_proto_depIdxs = []int32{
	7,  // 0: proto.GDRs.GDRs:type_name -> proto.GDRs.GDRsEntry
	0,  // 1: proto.GDR.timestamp:type_name -> proto.Timestamp
	8,  // 2: proto.GDR.values:type_name -> proto.GDR.ValuesEntry
	9,  // 3: proto.GDR.flexValues:type_name -> proto.GDR.FlexValuesEntry
	10, // 4: proto.GCRs.GCRs:type_name -> proto.GCRs.GCRsEntry
	11, // 5: proto.GCR.meta:type_name -> proto.GCR.MetaEntry
	0,  // 6: proto.GCR.timestamp:type_name -> proto.Timestamp
	12, // 7: proto.GCR.flexDefinitions:type_name -> proto.GCR.FlexDefinitionsEntry
	2,  // 8: proto.GDRs.GDRsEntry.value:type_name -> proto.GDR
	3,  // 9: proto.GDR.FlexValuesEntry.value:type_name -> proto.FlexValue
	5,  // 10: proto.GCRs.GCRsEntry.value:type_name -> proto.GCR
	6,  // 11: proto.GCR.FlexDefinitionsEntry.value:type_name -> proto.FlexDefinition
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_ksem_proto_init() }
func file_ksem_proto_init() {
	if File_ksem_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ksem_proto_rawDesc), len(file_ksem_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ksem_proto_goTypes,
		DependencyIndexes: file_ksem_proto_depIdxs,
		MessageInfos:      file_ksem_proto_msgTypes,
	}.Build()
	File_ksem_proto = out.File
	file_ksem_proto_goTypes = nil
	file_ksem_proto_depIdxs = nil
}
